# Production overlay Kustomization for alloy.
#
# Full HA configuration with increased resources.
resources:
  - ../../apps
patches:
  - path: base-patch.yaml
    target:
      kind: HelmRelease
      name: alloy-base
  - path: platform-patch.yaml
    target:
      kind: HelmRelease
      name: alloy-platform
