# Staging patch for alloy base chart.
#
# Reduces resource limits for cost-effective staging.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy-base
  namespace: flux-system
spec:
  values:
    alloy:
      alloy:
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
